autocmd  ColorScheme  *  highlight  VimgdbBreakpoint          ctermfg=Red   ctermbg=None  cterm=Bold
autocmd  ColorScheme  *  highlight  VimgdbDisabledBreakpoint  ctermfg=238   ctermbg=None  cterm=Bold
autocmd  ColorScheme  *  highlight  VimgdbLocation            ctermfg=None  ctermbg=238   cterm=None

highlight  VimgdbBreakpoint          ctermfg=Red   ctermbg=None  cterm=Bold
highlight  VimgdbDisabledBreakpoint  ctermfg=238   ctermbg=None  cterm=Bold
highlight  VimgdbLocation            ctermfg=None  ctermbg=238   cterm=None

sign  define  VimgdbBreakpointSign          text=⛔                 texthl=VimgdbBreakpoint
sign  define  VimgdbDisabledBreakpointSign  text=⛔                 texthl=VimgdbDisabledBreakpoint
sign  define  VimgdbLocationSign            linehl=VimgdbLocation
sign  define  VimgdbDummy

set shortmess=a
set sidescroll=1
set sidescrolloff=10
set scrolloff=10
set number
set lazyredraw

