autocmd  ColorScheme  *  highlight  VimgdbBreakpoint          ctermfg=Red   ctermbg=None  cterm=Bold
autocmd  ColorScheme  *  highlight  VimgdbDisabledBreakpoint  ctermfg=238   ctermbg=None  cterm=Bold
autocmd  ColorScheme  *  highlight  VimgdbLocation            ctermfg=None  ctermbg=238   cterm=None

highlight  VimgdbBreakpoint          ctermfg=Red   ctermbg=None  cterm=Bold
highlight  VimgdbDisabledBreakpoint  ctermfg=238   ctermbg=None  cterm=Bold
highlight  VimgdbLocation            ctermfg=None  ctermbg=238   cterm=None

sign  define  VimgdbBreakpointSign        text=⛔                 texthl=VimgdbBreakpoint
sign  define  VimgdbPasiveBreakpointSign  text=⛔                 texthl=VimgdbPasiveBreakpoint
sign  define  VimgdbLocationSign          linehl=VimgdbLocation
sign  define  VimgdbDummy

set shortmess=a
set sidescroll=1
set sidescrolloff=10
set scrolloff=10
set cmdheight=1
set number

